# Generated by Django 4.1.6 on 2023-02-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_post_time_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.FileField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
