# Generated by Django 4.1.6 on 2023-02-13 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-time_up']},
        ),
    ]
