# Generated by Django 4.1.6 on 2023-02-17 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_contact_contact_network_con_up_time_31ed8f_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='followed',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='follower',
        ),
        migrations.AddField(
            model_name='contact',
            name='user_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='user_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
