# Generated by Django 4.1.6 on 2023-02-17 22:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_remove_contact_followed_remove_contact_follower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='network.Contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
