# Generated by Django 4.1.6 on 2023-02-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_remove_contact_follower_contact_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='followers',
            new_name='follower',
        ),
    ]
