# Generated by Django 4.1.7 on 2023-03-27 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0018_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked_by",
                to="network.like",
            ),
        ),
    ]
