# Generated by Django 4.1.7 on 2023-03-28 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0022_alter_post_likes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="likes",
            new_name="liked_by",
        ),
    ]
