# Generated by Django 4.1.7 on 2023-03-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0023_rename_likes_post_liked_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="liked_by",
        ),
        migrations.AddField(
            model_name="post",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="liked_by", to="network.like"
            ),
        ),
    ]
