# Generated by Django 4.1.7 on 2023-03-28 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0025_alter_post_liked_by_delete_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="liked_by", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
