# Generated by Django 4.1.7 on 2023-03-28 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0026_alter_post_liked_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="liked_by",
            new_name="like",
        ),
    ]
